# Bootloader selection
BOOTLOADER = rp2040
CONVERT_TO=elite_pi

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
#RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
